- ReadMe.md
strategy and party games didn't seem the right category, leaving it to "family"; discretion advised for parents, as it is inspired by the works of H.P. Lovecraft
By submitting this pull request, **I promise** I 
- and ensured my submission includes:
[contrib-guidelines]: https://github.com/edm00se/awesome-board-games/blob/master/contributing.md
[all-issues]: https://github.com/edm00se/awesome-board-games/issues?utf8=%E2%9C%93&q=is%3Aissue
[open-prs]: https://github.com/edm00se/awesome-board-games/pulls
[new-issue]: https://github.com/edm00se/awesome-board-games/issues/new
[formatting-guide]: ../formatting.md
[readme-file]: ../readme.md
> adds Elder Sign

- ReadMe.md
By submitting this pull request, **I promise** I 
- the [contribution guidelines][contrib-guidelines]
- searched the [readme][readme-file] file
- searched the [open pull requests][open-prs]
- title
- description
- is in the/an appropriate category
- \# of players
- minimum age
- approximate play time
- a name of this which follows the naming convention of "adding"/"correcting" "&lt;game name&gt;"
- your changes is formatted as outlined in [the formatting guide][formatting-guide]
[contrib-guidelines]: https://github.com/edm00se/awesome-board-games/blob/master/contributing.md
[all-issues]: https://github.com/edm00se/awesome-board-games/issues?utf8=%E2%9C%93&q=is%3Aissue
[open-prs]: https://github.com/edm00se/awesome-board-games/pulls
[new-issue]: …
> adds mansions of madness 2nd ed

- .github/pull_request_template.md
- .gitignore
- .travis.yml
- .vuepress/config.js
- .vuepress/override.styl
- CNAME
- ReadMe.md
- code-of-conduct.md
- contributing.md
- help.md
- package-lock.json
- package.json
A bit of an overhaul, which achieves the following:
- provides a GitHub Pages version of the site, rendered entirely via [vuepress](https://vuepress.vuejs.org)
- decreases the amount of content in the PR template, it should be inviting, not dissuading people to contribute
- introduces a Travis CI build config, along with npm scripts to perform dev, build, and deploy to GitHub Pages
- corrects contact link in code of conduct
> Major Structural Overhaul

- .travis.yml
- readme.md
shoves task into travis config to restore it for themeing
> removes yaml front matter from readme.md

- readme.md
added Munchkin for [#10](https://github.com/edm00se/awesome-board-games/issues/10).
> added Munchkin

- readme.md
> Adding Game of Thrones Board Game

- readme.md
> fix: Game of Thrones broken link

- readme.md
Added description of Ludo Game for issue #10 
> Added Ludo Game for issue #10 

- readme.md
> adding 2 player game YINSH

- readme.md
Once your PR is created, it will trigger a build on Travis CI. This includes a formatter linting process, so if there are any issues with the build, please address them.
#10
> Add Anachrony, Cthulhu Wars, Clockwork Wars

- readme.md
> adding Tak

- readme.md
> Add `Contrast`

- readme.md
> #10 Who wants to be a millionare?

- readme.md
> Add sushi GO

- readme.md
> add exploding kittens

- readme.md
> add complots

- readme.md
> add Shabadabada

- readme.md
> add Jungle Speed

- readme.md
Added chess board game to the list
> Added chess board game

- readme.md
> add carrom

- readme.md
> add Antike Duellum

- .vuepress/config.js
adds ga tracking, for those un-blocked browsers
fixes #45
> feat(analytics): adds google analytics tracking

- readme.md
A great 2-player adaptation which deserves to be alongside the main original (which is the main game  I use to draw people into gaming by the way)
> Add ‘7 wonders Duel’

- readme.md
> Added Spirit Island

- package-lock.json
- package.json
- readme.md
> Fix(img): one night warewolf

- readme.md
> Added the game Commons Poly

- readme.md
Fixes #59 
- [x ] searched the [readme][readme] file and searched the [open pull requests](https://github.com/edm00se/awesome-board-games/pulls) (no duplicates please)
- [ x] and will follow [the desired format][format-guide]
- [ x] used image links that resolve correctly, are appropriately sized, and are served over HTTPS
> Added Twilight Imperium 4th Edition

- readme.md
(https://github.com/edm00se/awesome-board-games/pull/63)
> Added cluedo

- readme.md
> Added Monopoly

- readme.md
> Added Terror Below

- readme.md
How do you resize the images from boardgamegeeks? If I try to change the size in the URL I only get HTTP error 400
-------------
> Added Sheriff of Nottingham

- readme.md
> Added Exit The Game the Abandoned Cabin

- readme.md
> Adding Secret Hitler.

- readme.md
> Added smash up

- readme.md
> Added Telestrations

- readme.md
> added codenames

- readme.md
> added Splendor to list?

- readme.md
> adding candyland

- readme.md
> Added Persian Wars game

- readme.md
> Add Ghost Blitz awosome board game for family

- readme.md
> Adds Superfight

- readme.md
> Added Love Letter

- readme.md
> adding TZAAR to Readme.md

- readme.md
> Added Pitch 'n' Pass Game to readme file

- readme.md
> add cranium game

- readme.md
> Adds Sorry and Mastermind

- readme.md
> adds Call to Adventure

- readme.md
> Add Mind the Gap

- package-lock.json
> chore(deps): updates sec deps

- readme.md
> Adding Battleball.

- readme.md
Thank you for making this repo, this is such a cool initiative. :)
I saw #131 and wanted to pitch in with **Stone Age**, a game that brings me fond memories of hanging out at a local board game cafe.
---------
> Add Stone Age

- readme.md
Came across https://github.com/edm00se/awesome-board-games/issues/131 while searching Hacktoberfest issues and would like to add a favorite board game: Parcheesi.
> add Parcheesi to awesome-board-games readme

- readme.md
> Add Forbidden Sky

- readme.md
> Add Santorini

- readme.md
> Add Tokaido

- readme.md
Submitting this PR means I have:
> Add Chutes and Ladders

- package-lock.json
> chore(deps): updates nested deps

- help.md
- package-lock.json
- package.json
- readme.md
> CI automatic check for dead links

- readme.md
This PR is for Hacktoberfest #176
> added Rat-a-Tat Cat game

- readme.md
This PR is for Hacktoberfest #176
> Added Blokus game

- readme.md
> add: Unanimo Party

- readme.md
> Add Axis & Allies to Strategy Category

- readme.md
> fix(lint): updates axis & allies image url

- readme.md
Thanks! Scrabble Game
---
@edm00se ready for review
> Added Scrabble into game list

- readme.md
> Add Chinese Checkers to Strategy Category 

- readme.md
The board consists of a grid with twenty-four intersections or points. Each player has nine pieces, or "men", usually coloured black and white. Players try to form 'mills'—three of their own men lined horizontally or vertically—allowing a player to remove an opponent's man from the game. A player wins by reducing the opponent to two pieces (where they could no longer form mills and thus be unable to win), or by leaving them without a legal move.
this is for hacktoberfest #176
> Added Nine men's morris

- readme.md
> Adds Telepathy strategy game

- readme.md
> Add Small World to strategy board game list

- .github/workflows/wip.yml
- readme.md
This PR is for Hacktoberfest #176.
> Add The Estates

- readme.md
> Added Say What? Shiok Food Card Game

- readme.md
> Added Rising Sun

- .vitepress/config.js
fixes #233
Looks to work on local. Update: also works in the vercel preview.
> fix(search): algolia migration managed

- readme.md
> Added Ayoayo

- readme.md
Adding the Italian strategy board game Condottiere
> adding Condottiere

- readme.md
> Adds Dungeon Mayhem

- readme.md
> Adds Decrypto

- readme.md
add Hidden Leaders game. 
This was done as part of Hacktoberfest2022! #230
> add Hidden Leaders game

- readme.md
> added Pax Viking

- readme.md
> Adds Jackal

- readme.md
> Cleaning up typos

- readme.md
> Add Talisman

- readme.md
url seems down, breaking awesome-lint
> updates superfight url

- package-lock.json
- package.json
Closes #265, #266, #267. Confirmed working w/ `npm run lint` and `npm run lint-md`.
> chore(deps): updates dev deps

- readme.md
- [ *] searched the [readme][readme-url] file and searched the [open pull requests][pr-url] (no duplicates please)
- [ *] and will follow [the desired format][format-url]
- [ *] used image links that resolve correctly, are appropriately sized, and are served over HTTPS
[readme-url]: …
> Adding game: The Witcher: Old World

- readme.md
> add magic: the gathering

- readme.md
> Added Ambush board game

- readme.md
> Added Queen Guard or Agon or Royal Guard board game

- readme.md
> Added Android Netrunner board game

- readme.md
> Added Eclipse: Second Dawn Galaxy board game

- readme.md
> Added The Castles of Burgundy board game

- readme.md
> Added Through the Ages: A new story go civilization board game

- readme.md
> Added Great Western Trials board game

- readme.md
> Added Twilight Struggle board game

- readme.md
> Added Brass: Birmingham board game

- readme.md
> Added Gaia Project board game

- readme.md
> Added Snake Oil board game

- readme.md
> added Blood on the Clocktower board game

- readme.md
> Added Just One board game

- readme.md
> Add Splendor Duel

- readme.md
> Added Wits & Wagers board game

- readme.md
> Add Power Grid

- readme.md
> Add The Quacks of Quedlinburg

- readme.md
> Add The Quest for El Dorado

- readme.md
> Add Cascadia

- readme.md
> Add Crokinole

- readme.md
> Add Lost Ruins of Arnak

- readme.md
> Add Heat: Pedal to the Metal

- readme.md
> Add The Crew: Mission Deep Sea

- readme.md
> Add Wingspan Asia

- readme.md
> Add Welcome to the Moon

- readme.md
> Add The Isle of Cats

- readme.md
> Add Patchwork

- readme.md
> Add Wingspan

- readme.md
> Add Everdell

- readme.md
> Add Cartographers

- readme.md
> add Monikers board game

- readme.md
> Geek Out! board game added

- readme.md
> Animocrazy board game added

- readme.md
> Kragmortha board game added

- readme.md
> Added Blue and Gray

- readme.md
> Added Bagh Chal

- readme.md
> Added Shogi(Japanese Chess)

- readme.md
> Add Istanbul

- readme.md
> Add Clank!: Catacombs

- readme.md
> Add Azul: Summer Pavilion

- readme.md
> moves azul summer pavilion to be adjacent to the original

- readme.md
> Add That's Pretty Clever!

- readme.md
> Added Orleans board games

- readme.md
> Added Barrage board games

- readme.md
> Added argicola board games

- readme.md
> Added pax-pamir second edition board games

- readme.md
> Added Too Many Bones board games

- readme.md
> Added root board games

- readme.md
> Added pandemic legacy board games

- readme.md
> Added food chain magnate board games

- readme.md
> Added mage knight board board games

- readme.md
> Added underwater cities board games

- readme.md
> Added on marsboard games

- readme.md
> Added lisboaboard games

- readme.md
> Added viticulture board games

- readme.md
> Added Caverna: The cave farmers board games

- readme.md
> Added maracaibo  board games

- readme.md
> Added puerto rico  board games

- readme.md
> Added blood rageboard games

- readme.md
> Added the gallerist board games

- readme.md
> Added paladins of the west kingdom board games

- readme.md
> Added clans fo caledonia board games

- readme.md
> Added Le Havre board games

- readme.md
> Added Grand Austria Hotel board games

- readme.md
> Added Mechs vs Minions board games

- readme.md
> Added fields of arle board games

- readme.md
> Added obsession board games

- readme.md
> Added The Crew: The Quest for Planet Nine board games

- readme.md
> Added Tzolkin: The Mayan Calendar board games

- readme.md
> Added Concordia Venus board games

- readme.md
> Added The Beyound the Sun  board games

- readme.md
> Added The Forever War

- readme.md
> Adding The Book of Pop-Up Board Games (1996)

- readme.md
> Adding Jenga and Mouse Trap board game

- readme.md
> Added Dice Forge

- readme.md
> Added  Contigo

- readme.md
I have added Kemet Board Game in the readme file.
> Added Kemet

- readme.md
I have added Photosynthesis board game in the readme file.
> Add Photosynthesis

- readme.md
> Added Paperback

- readme.md
> Added Space Alert

- readme.md
> Added Imperial Settlers

- readme.md
> Added Nemo's War

- readme.md
Not sure if `party` is the best category but didn't see an adventure or role-playing one. 🤷‍♂️
https://github.com/edm00se/awesome-board-games/issues/269
[format-url]: …
> Add The Lord of the Rings

- readme.md
> Add Dominion

- readme.md
> Added Arkham Horror game

- readme.md
> Added Caylus | MultiPlayer Game

- readme.md
> added Falling Koalas

- readme.md
> five tribes

- readme.md
> Added Calico Game

- readme.md
> Added Paleo game

- readme.md
> Added Skull game

- readme.md
Added the board game - Kill Doctor Lucky
(New game, checked for duplicates, none found; updated all according to specified conditions)
> Added the board game - Kill Doctor Lucky

- readme.md
> Added a Keyflower Board Game

- readme.md
Hi, I want to contribute to this Repository. I have added a new Board Game "Star Wars" in this ReadMe file. Please see if this addition can be merged against label HacktoberFest 2023. Thank you so much.
Saumya
When you're ready, check off the above …
> Adds Star Wars: The Deckbuilding Game

- readme.md
> Added new game Chaupar

- readme.md
Once your PR is created, it will trigger a build a couple of automated checks, including a GitHub Action (Awesome-Lint). This includes a format linting process, so if there are any issues with the build, please address them. The others include a check on the submission limit and also a preview of the site with your changes; please check them out, they are tools to help us both. …
> Adding Game: Saboteur

- readme.md
Hi, I want to contribute to this Repository. I have added a new Board Game "The Gilded Realms" in this ReadMe file. Please see if this addition can be merged against label HacktoberFest 2023. Thank you so much.
Shilpi
When you're ready, check off the above …
> Added The Gilded Realms

- readme.md
HI,
I have added another game "Zoo Vadis" to the ReadMe. Please see if this can be merged under HacktoberFest. Thank you.
[contributing-url]: …
> Added Zoo Vadis game

- readme.md
Once your PR is created, it will trigger a build a couple of automated checks, including a GitHub Action (Awesome-Lint). This includes a format linting process, so if there are any issues with the build, please address them. The others include a check on the submission limit and also a preview of the site with your changes; please check them out, they are tools to help us both. …
> Adding game: The Last Bottle of Rum

- readme.md
> Added game Twilight Inscription

- readme.md
Hi,
I have now taken ReadMe again and added this new game . Please see if you merge this contribution against Hacktoberfest. As just 1 more PR need to be completed for completing 4 contributions in Hacktoberfest event, please see if you can merge it fast. Thank you so much for considering. It would be a great help. Raising a new PR in order to avoid any further problem.
Do you …
> Added "Hadrian's Wall" game

- .github/workflows/update-deps.yml
- readme.md
> ci(action): provides action to attempt to automatically update npm deps

- readme.md
This is a lovely project, im fairly new to github, so if any changes are needed let me know. Cheers!
- [ :-) ] reviewed the [contributing][contributing-url] document and are comfortable understanding what it says
- [  :-) ] searched the [readme][readme-url] file and searched the [open pull requests][pr-url] (no duplicates please)
- [  :-) ] and will follow [the desired format][format-url]
- [ :-)  ] used image links that resolve correctly, are appropriately sized, and are served over HTTPS
- [  :-) ] read [this year's Hacktoberfest welcome issue](https://github.com/edm00se/awesome-board-games/issues/269)
- [ :-)  ] promised not to `@` me asking for review (I will see the notifications already, no need to add noise)
> Added a new board game, Quoridor, to the strategy section of readme! cheers

- .github/workflows/lint.yml
- code-of-conduct.md
- package-lock.json
- package.json
- readme.md
> chore(ci): bumps lint.yml node to v22 lts

- formatting.md
> chore(docs): updates formatting.md w/ updated titlecase link

- .github/workflows/janet.yml
- readme.md
for review
Time to summon Janet.
dang
> Update janet.yml to use forked and updated node version

- readme.md
>  Update Takenoko into readme.md
